apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yashjskj/frontend:latest
          ports:
            - containerPort: 3000

