apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yashjskj/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              value: mongodb://root:example@mongodb:27017/mydatabase
