apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: multi-service-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mongodb
