apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-new  # Change the name
  namespace: multi-service-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
