apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: multi-service-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017 # Exposes the service on this port
  type: NodePort
