apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc # The name of the PVC that will be referenced by the deployment
  namespace: multi-service-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual # Matches the PV storage class
